buildjob:
    stage: build
    tags:
      - project2-runner
    script:
      - docker build -t image:latest .
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
      - docker push image:latest
      - aws ecs update-service --cluster project2-cluster --service project2-service --force-new-deployment
